

image: php:7.2-fpm

pipelines:
  branches:
    dev:
      - step:
          script:
            - apt-get update && apt-get install -qy git curl libmcrypt-dev libpq-dev
            - yes | pecl install mcrypt-1.0.1
            - docker-php-ext-install pdo pdo_pgsql
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - ln -f -s .env.pipelines .env
            - php artisan migrate
            - php artisan serve &
            - sleep 5
            - ./vendor/bin/phpunit
            - curl -vk http://localhost:8000
          services:
            - postgres

definitions:
  services:
    postgres:
      image: postgres:12
      environment:
        POSTGRES_DB: mabeei
        POSTGRES_USER: mabeei
        POSTGRES_PASSWORD: mabeei